// Known heist curio display items — these are the ONLY item types that appear
// in curio displays. Having explicit lists means we can match with high confidence.

export const EXPERIMENTED_BASES: string[] = [
  // One-handed Axes
  'Disapprobation Axe',
  'Psychotic Axe',
  // Two-handed Axes
  'Honed Cleaver',
  'Apex Cleaver',
  // Bows
  'Foundry Bow',
  'Solarine Bow',
  // Claws
  'Malign Fangs',
  'Void Fangs',
  // Daggers
  'Pressurised Dagger',
  'Pneumatic Dagger',
  // Rune Daggers
  'Flashfire Blade',
  'Infernal Blade',
  // One-handed Maces
  'Crack Mace',
  'Boom Mace',
  // Sceptres
  'Oscillating Sceptre',
  'Stabilising Sceptre',
  'Alternating Sceptre',
  // Two-handed Maces
  'Crushing Force Magnifier',
  'Impact Force Propagator',
  // Staves
  'Reciprocation Staff',
  'Battery Staff',
  // Warstaves
  'Potentiality Rod',
  'Eventuality Rod',
  // One-handed Swords
  'Capricious Spiritblade',
  'Anarchic Spiritblade',
  // Two-handed Swords
  'Blasting Blade',
  'Banishing Blade',
  // Wands
  'Congregator Wand',
  'Accumulator Wand',
  // Armour Shields
  'Magmatic Tower Shield',
  'Heat-attuned Tower Shield',
  // Evasion Shields
  'Polar Buckler',
  'Cold-attuned Buckler',
  // ES Shields
  'Subsuming Spirit Shield',
  'Transfer-attuned Spirit Shield',
  // Belts
  'Micro-Distillery Belt',
  'Mechanical Belt',
  // Amulets
  'Focused Amulet',
  'Simplex Amulet',
  'Astrolabe Amulet',
  // Rings
  'Cogwork Ring',
  'Composite Ring',
  'Geodesic Ring',
  'Helical Ring',
  'Manifold Ring',
  'Ratcheting Ring',
];

export const REPLICA_UNIQUES: string[] = [
  'Replica Abyssus',
  'Replica Advancing Fortress',
  "Replica Alberon's Warpath",
  'Replica Allelopathy',
  'Replica Allure',
  "Replica Alpha's Howl",
  "Replica Ambu's Charge",
  "Replica Atziri's Acuity",
  "Replica Atziri's Foible",
  'Replica Badge of the Brotherhood',
  'Replica Bated Breath',
  'Replica Bitterdream',
  'Replica Blood Sacrifice',
  'Replica Blood Thorn',
  'Replica Bloodplay',
  'Replica Bones of Ullr',
  'Replica Cheap Construction',
  'Replica Cold Iron Point',
  "Replica Conqueror's Efficiency",
  'Replica Cortex',
  'Replica Covenant',
  "Replica Doedre's Damning",
  'Replica Dreamfeather',
  'Replica Duskdawn',
  "Replica Earendel's Embrace",
  'Replica Emberwake',
  'Replica Eternity Shroud',
  "Replica Farrul's Fur",
  'Replica Fencoil',
  'Replica Forbidden Shako',
  'Replica Fragile Bloom',
  'Replica Fragility',
  'Replica Frostbreath',
  'Replica Gifts from Above',
  'Replica Grip of the Council',
  'Replica Harvest',
  'Replica Headhunter',
  'Replica Heartbreaker',
  'Replica Heatshiver',
  "Replica Hinekora's Sight",
  'Replica Hotheaded',
  "Replica Hyrri's Ire",
  "Replica Hyrri's Truth",
  'Replica Infractem',
  'Replica Innsbury Edge',
  "Replica Inya's Epiphany",
  'Replica Iron Commander',
  "Replica Kalisa's Grace",
  "Replica Kaom's Heart",
  'Replica Karui Ward',
  "Replica Kongor's Undying Rage",
  'Replica Last Resort',
  "Replica Lavianga's Spirit",
  'Replica Leer Cast',
  "Replica Lioneye's Paws",
  'Replica Loreweave',
  "Replica Malachai's Artifice",
  "Replica Maloney's Mechanism",
  'Replica Midnight Bargain',
  'Replica Mistwall',
  'Replica Nebulis',
  "Replica Oro's Sacrifice",
  'Replica Pacifism',
  'Replica Paradoxica',
  'Replica Perfect Form',
  'Replica Pillars of Arun',
  "Replica Poorjoy's Asylum",
  'Replica Powerlessness',
  'Replica Primordial Might',
  'Replica Prismweave',
  'Replica Pure Talent',
  'Replica Quill Rain',
  'Replica Reckless Defence',
  'Replica Red Trail',
  'Replica Restless Ward',
  "Replica Rumi's Concoction",
  'Replica Shroud of the Lightless',
  'Replica Siegebreaker',
  'Replica Sorrow of the Divine',
  'Replica Soul Strike',
  'Replica Soul Tether',
  "Replica Tulfall",
  "Replica Volkuur's Guidance",
  'Replica Winterheart',
  "Replica Witchfire Brew",
  "Replica Wyrmsign",
];
